MONITORED_PROCESS = [
"ApplicationFrameHost.exe",
"LMS.exe",
"Memory Compression",
"NVDisplay.Container.exe",
"OfficeClickToRun.exe",
"RegAsm.exe",
"Registry",
"Regsvr32.exe",
# "RuntimeBroker.exe",
"SecurityHealthService.exe",
"SecurityHealthSystray.exe",
"SgrmBroker.exe",
"ShellExperienceHost.exe",
"StartMenuExperienceHost.exe",
"System",
"System Idle Process",
# "WmiPrvSE.exe",
"calc.exe",
# "conhost.exe",
# "csrss.exe",
"ctfmon.exe",
# "dllhost.exe",
"dwm.exe",
"explorer.exe",
# "fontdrvhost.exe",
"lsass.exe",
"mavinject.exe",
"mimikatz.exe",
"mshta.exe",
"msiexec.exe",
"notepad.exe",
"powershell.exe",
"python.exe",
"regsvcs.exe",
"regsvr32.exe",
"ruby.exe",
"rundll32.exe",
"services.exe",
"sihost.exe",
"smss.exe",
"spoolsv.exe",
# "svchost.exe",
"taskhost.exe",
"taskhostw.exe",
# "werfault.exe",
"wininit.exe",
"winlogon.exe",
"cmd.exe",
]
