FEATURE_SET = [
    # "LMS.exe_memory_percent",
    # "LMS.exe_nonpaged_pool",
    "LMS.exe_num_handles",
    "LMS.exe_paged_pool",
    "LMS.exe_pagefile",
    # "LMS.exe_peak_nonpaged_pool",
    "LMS.exe_peak_paged_pool",
    "LMS.exe_peak_pagefile",
    "LMS.exe_peak_wset",
    "LMS.exe_user",
    # "LMS.exe_voluntary",
    # "OfficeClickToRun.exe_nonpaged_pool",
    "OfficeClickToRun.exe_paged_pool",
    "OfficeClickToRun.exe_peak_nonpaged_pool",
    # "OfficeClickToRun.exe_peak_paged_pool",
    # "SecurityHealthService.exe_memory_percent",
    # "SecurityHealthService.exe_nonpaged_pool",
    "SecurityHealthService.exe_num_handles",
    "SecurityHealthService.exe_paged_pool",
    "SecurityHealthService.exe_pagefile",
    "SecurityHealthService.exe_peak_nonpaged_pool",
    # "SecurityHealthService.exe_peak_paged_pool",
    "SecurityHealthService.exe_peak_pagefile",
    "SecurityHealthService.exe_peak_wset",
    "SecurityHealthService.exe_read_bytes",
    "SecurityHealthService.exe_read_count",
    "SecurityHealthService.exe_user",
    "SecurityHealthService.exe_write_bytes",
    "SecurityHealthService.exe_write_count",
    "SecurityHealthSystray.exe_ionice",
    # "SecurityHealthSystray.exe_memory_percent",
    "SecurityHealthSystray.exe_nonpaged_pool",
    "SecurityHealthSystray.exe_num_handles",
    "SecurityHealthSystray.exe_paged_pool",
    "SecurityHealthSystray.exe_pagefile",
    # "SecurityHealthSystray.exe_peak_paged_pool",
    "SecurityHealthSystray.exe_peak_pagefile",
    "SecurityHealthSystray.exe_peak_wset",
    "SecurityHealthSystray.exe_rss",
    "SecurityHealthSystray.exe_system",
    "SecurityHealthSystray.exe_user",
    # "SgrmBroker.exe_nonpaged_pool",
    "SgrmBroker.exe_num_handles",
    # "SgrmBroker.exe_peak_nonpaged_pool",
    "SgrmBroker.exe_peak_paged_pool",
    "SgrmBroker.exe_peak_pagefile",
    "SgrmBroker.exe_peak_wset",
    "ShellExperienceHost.exe_ionice",
    # "ShellExperienceHost.exe_memory_percent",
    # "ShellExperienceHost.exe_nonpaged_pool",
    "ShellExperienceHost.exe_num_handles",
    "ShellExperienceHost.exe_paged_pool",
    "ShellExperienceHost.exe_pagefile",
    # "ShellExperienceHost.exe_peak_nonpaged_pool",
    # "ShellExperienceHost.exe_peak_paged_pool",
    "ShellExperienceHost.exe_peak_pagefile",
    "ShellExperienceHost.exe_peak_wset",
    "ShellExperienceHost.exe_system",
    "ShellExperienceHost.exe_user",
    "StartMenuExperienceHost.exe_peak_nonpaged_pool",
    "calc.exe_nice",
    "calc.exe_num_handles",
    "ctfmon.exe_ionice",
    # "ctfmon.exe_memory_percent",
    # "ctfmon.exe_nonpaged_pool",
    "ctfmon.exe_num_handles",
    "ctfmon.exe_paged_pool",
    "ctfmon.exe_pagefile",
    "ctfmon.exe_peak_nonpaged_pool",
    # "ctfmon.exe_peak_paged_pool",
    "ctfmon.exe_peak_pagefile",
    "ctfmon.exe_peak_wset",
    "ctfmon.exe_rss",
    "explorer.exe_peak_wset",
    "lsass.exe_connections_info",
    # "lsass.exe_memory_percent",
    # "lsass.exe_nonpaged_pool",
    "lsass.exe_num_handles",
    "lsass.exe_paged_pool",
    "lsass.exe_pagefile",
    "lsass.exe_peak_nonpaged_pool",
    "lsass.exe_peak_paged_pool",
    "lsass.exe_peak_pagefile",
    "lsass.exe_peak_wset",
    "mshta.exe_other_count",
    "mimikatz.exe_peak_nonpaged_pool",
    "msiexec.exe_connections_info",
    "powershell.exe_connections_info",
    "powershell.exe_ionice",
    # "powershell.exe_memory_percent",
    "powershell.exe_nice",
    # "powershell.exe_nonpaged_pool",
    "powershell.exe_num_handles",
    "powershell.exe_num_page_faults",
    # "powershell.exe_other_bytes",
    "powershell.exe_other_count",
    "powershell.exe_paged_pool",
    "powershell.exe_pagefile",
    "powershell.exe_peak_nonpaged_pool",
    # "powershell.exe_peak_paged_pool",
    "powershell.exe_peak_pagefile",
    "powershell.exe_peak_wset",
    "powershell.exe_private",
    "powershell.exe_read_bytes",
    "powershell.exe_read_count",
    "powershell.exe_rss",
    "powershell.exe_system",
    "powershell.exe_user",
    "powershell.exe_vms",
    # "powershell.exe_voluntary",
    "powershell.exe_write_bytes",
    "powershell.exe_write_count",
    "powershell.exe_wset",
    "python.exe_connections_info",
    # "python.exe_ionice",
    # "powershell.exe_memory_percent",
    # "python.exe_nice",
    # "powershell.exe_nonpaged_pool",
    # "python.exe_num_handles",
    # "python.exe_num_page_faults",
    # "powershell.exe_other_bytes",
    # "python.exe_other_count",
    # "python.exe_paged_pool",
    # "python.exe_pagefile",
    # "python.exe_peak_nonpaged_pool",
    # "powershell.exe_peak_paged_pool",
    # "python.exe_peak_pagefile",
    # "python.exe_peak_wset",
    # "python.exe_private",
    # "python.exe_read_bytes",
    # "python.exe_read_count",
    # "python.exe_rss",
    # "python.exe_system",
    # "python.exe_user",
    # "python.exe_vms",
    "regsvr32.exe_num_handles",
    "ruby.exe_connections_info",
    # "ruby.exe_memory_percent",
    # "ruby.exe_nonpaged_pool",
    "ruby.exe_num_handles",
    "ruby.exe_paged_pool",
    "ruby.exe_pagefile",
    "ruby.exe_peak_nonpaged_pool",
    "ruby.exe_peak_paged_pool",
    "ruby.exe_peak_pagefile",
    "ruby.exe_peak_wset",
    "rundll32.exe_num_handles",
    "services.exe_connections_info",
    "services.exe_memory_percent",
    "services.exe_nonpaged_pool",
    "services.exe_num_handles",
    "services.exe_paged_pool",
    "services.exe_pagefile",
    "services.exe_peak_nonpaged_pool",
    # "services.exe_peak_paged_pool",
    "services.exe_peak_pagefile",
    "services.exe_peak_wset",
    "sihost.exe_ionice",
    # "sihost.exe_memory_percent",
    # "sihost.exe_nonpaged_pool",
    "sihost.exe_num_handles",
    "sihost.exe_paged_pool",
    "sihost.exe_pagefile",
    "sihost.exe_peak_nonpaged_pool",
    # "sihost.exe_peak_paged_pool",
    "sihost.exe_peak_pagefile",
    "sihost.exe_peak_wset",
    # "smss.exe_memory_percent",
    # "smss.exe_nonpaged_pool",
    "smss.exe_pagefile",
    "smss.exe_peak_pagefile",
    "smss.exe_peak_wset",
    "smss.exe_rss",
    "smss.exe_system",
    # "smss.exe_voluntary",
    "spoolsv.exe_connections_info",
    # "spoolsv.exe_memory_percent",
    # "spoolsv.exe_nonpaged_pool",
    "spoolsv.exe_num_handles",
    "spoolsv.exe_paged_pool",
    "spoolsv.exe_pagefile",
    "spoolsv.exe_peak_nonpaged_pool",
    # "spoolsv.exe_peak_paged_pool",
    "spoolsv.exe_peak_pagefile",
    "spoolsv.exe_peak_wset",
    "spoolsv.exe_system",
    "spoolsv.exe_user",
    # "spoolsv.exe_voluntary",
    "taskhostw.exe_ionice",
    # "taskhostw.exe_memory_percent",
    "taskhostw.exe_num_handles",
    "taskhostw.exe_paged_pool",
    # "taskhostw.exe_peak_paged_pool",
    "taskhostw.exe_peak_wset",
    "wininit.exe_connections_info",
    # "wininit.exe_memory_percent",
    # "wininit.exe_nonpaged_pool",
    "wininit.exe_num_handles",
    "wininit.exe_paged_pool",
    "wininit.exe_pagefile",
    "wininit.exe_peak_nonpaged_pool",
    # "wininit.exe_peak_paged_pool",
    "wininit.exe_peak_pagefile",
    "wininit.exe_peak_wset",
    "wininit.exe_rss",
    "wininit.exe_system",
    "wininit.exe_user",
    # "wininit.exe_voluntary",
    # "winlogon.exe_memory_percent",
    # "winlogon.exe_nonpaged_pool",
    "winlogon.exe_num_handles",
    "winlogon.exe_paged_pool",
    "winlogon.exe_pagefile",
    "winlogon.exe_peak_nonpaged_pool",
    # "winlogon.exe_peak_paged_pool",
    "winlogon.exe_peak_pagefile",
    "winlogon.exe_peak_wset",
    "winlogon.exe_system",
    "winlogon.exe_user",
    # "winlogon.exe_voluntary",
]
